print("Hi, my name is Introduction. Nice to meet you!")
name=input("What's your name?")
print("Hello",name)
hobby= input("What is your hobby_1?")
print("That's a nice hobby,",hobby,"is my favorites hobby too")
holiday=input("Where is your favorite holiday destination?")
print("That's one of best place you can visit.")